package com.seu.socialworkcards;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.view.inputmethod.InputMethodManager;import android.widget.*;import org.json.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity {
    final int BG=Color.rgb(245,246,243), SURFACE=Color.WHITE, INK=Color.rgb(38,51,45), MUTED=Color.rgb(122,129,125), MINT=Color.rgb(68,184,159), MINT_SOFT=Color.rgb(224,245,239), ORANGE=Color.rgb(230,104,59), RED_SOFT=Color.rgb(248,233,228), GOLD_SOFT=Color.rgb(248,242,223);
    CardRepository repo; StudyStore store; ReviewEngine engine; LinearLayout root,body,nav; List<Card> queue=new ArrayList<>(); int qIndex=0; boolean revealed=false;
    @Override public void onCreate(Bundle b){super.onCreate(b);try{repo=new CardRepository(this);store=new StudyStore(this);engine=new ReviewEngine(store);showReview();}catch(Exception e){TextView t=new TextView(this);t.setText("启动失败："+e);setContentView(t);}}
    int dp(int x){return (int)(x*getResources().getDisplayMetrics().density+.5f);} GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
    TextView tv(String s,int sp,int c,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(c);v.setLineSpacing(0,1.18f);if(bold)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}
    Button btn(String s,int bgc,int tc){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(tc);b.setTextSize(14);b.setBackground(bg(bgc,12));return b;}
    void margin(View v,int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(l),dp(t),dp(r),dp(b));v.setLayoutParams(p);}
    LinearLayout box(int c,int pad,int rad){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(pad),dp(pad),dp(pad),dp(pad));l.setBackground(bg(c,rad));return l;}
    void shell(String title){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);setContentView(root);LinearLayout h=new LinearLayout(this);h.setPadding(dp(20),dp(14),dp(20),dp(8));h.addView(tv(title,25,INK,true));root.addView(h);ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(14),0,dp(14),dp(90));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));nav=new LinearLayout(this);nav.setOrientation(LinearLayout.HORIZONTAL);nav.setBackgroundColor(SURFACE);String[] ns={"复习","卡片","统计","我的"};for(String n:ns){Button b=new Button(this);b.setText(n);b.setAllCaps(false);b.setTextColor(MUTED);b.setBackgroundColor(Color.TRANSPARENT);b.setOnClickListener(v->{if(n.equals("复习"))showReview();else if(n.equals("卡片"))showBooks();else if(n.equals("统计"))showStats();else showSettings();});nav.addView(b,new LinearLayout.LayoutParams(0,dp(58),1));}root.addView(nav);}
    void ensureQueue(){if(queue.isEmpty()||qIndex>=queue.size()){int rr=Math.max(0,store.reviewGoal()-store.todayReview()),nn=Math.max(0,store.newGoal()-store.todayNew());queue=engine.dailyQueue(repo.cards,rr,nn);qIndex=0;revealed=false;}}
    void showReview(){shell("今日复习");ensureQueue();LinearLayout sum=new LinearLayout(this);sum.setOrientation(LinearLayout.HORIZONTAL);sum.addView(stat("复习",store.todayReview(),store.reviewGoal()),new LinearLayout.LayoutParams(0,-2,1));Space gap=new Space(this);sum.addView(gap,new LinearLayout.LayoutParams(dp(8),1));sum.addView(stat("新学",store.todayNew(),store.newGoal()),new LinearLayout.LayoutParams(0,-2,1));margin(sum,0,4,0,10);body.addView(sum);if(queue.isEmpty()){LinearLayout done=box(SURFACE,22,18);done.addView(tv("✓ 今日目标已完成",21,INK,true));done.addView(tv("可以去“卡片”中单独复习，或在“我的”调整每日数量。",14,MUTED,false));body.addView(done);return;}renderCard();}
    View stat(String label,int a,int b){LinearLayout l=box(SURFACE,13,16);l.addView(tv(a+" / "+b,24,MINT,true));l.addView(tv(label,12,MUTED,false));return l;}
    void renderCard(){Card c=queue.get(qIndex);StudyStore.State s=store.state(c.id);LinearLayout card=box(SURFACE,18,20);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,dp(500));cp.setMargins(0,0,0,dp(10));card.setLayoutParams(cp);card.addView(tv(c.kind,12,MINT,true));TextView q=tv(c.question,24,INK,true);q.setGravity(Gravity.CENTER_HORIZONTAL);margin(q,0,20,0,10);card.addView(q);ScrollView mid=new ScrollView(this);LinearLayout inner=new LinearLayout(this);inner.setOrientation(LinearLayout.VERTICAL);inner.setGravity(Gravity.CENTER_HORIZONTAL);inner.setPadding(dp(4),dp(14),dp(4),dp(10));if(!revealed){TextView hint=tv("请先主动回忆答案\n点击下方显示答案",17,Color.rgb(145,151,147),true);hint.setGravity(Gravity.CENTER);inner.addView(hint);}else{for(String x:c.bullets){TextView p=tv("• "+x,15,INK,false);margin(p,0,0,0,8);inner.addView(p);}TextView src=tv("出处："+c.origin,12,MUTED,false);margin(src,0,12,0,0);inner.addView(src);inner.addView(historyMini(c));}mid.addView(inner);card.addView(mid,new LinearLayout.LayoutParams(-1,0,1));LinearLayout tools=new LinearLayout(this);tools.setOrientation(LinearLayout.HORIZONTAL);Button ex=btn("例子",GOLD_SOFT,INK),full=btn("完整答案",MINT_SOFT,INK),hist=btn("近10次",Color.rgb(239,241,239),INK);ex.setEnabled(c.hasExample);full.setEnabled(c.hasLong);ex.setOnClickListener(v->showExample(c));full.setOnClickListener(v->showFull(c));hist.setOnClickListener(v->showHistory(c));tools.addView(ex,new LinearLayout.LayoutParams(0,dp(48),1));tools.addView(full,new LinearLayout.LayoutParams(0,dp(48),1));tools.addView(hist,new LinearLayout.LayoutParams(0,dp(48),1));card.addView(tools);body.addView(card);if(!revealed){Button r=btn("显示答案",MINT,Color.WHITE);r.setOnClickListener(v->{revealed=true;showReview();});body.addView(r,new LinearLayout.LayoutParams(-1,dp(54)));}else{LinearLayout rate=new LinearLayout(this);rate.setOrientation(LinearLayout.HORIZONTAL);Button bad=btn("不清楚",RED_SOFT,Color.rgb(130,70,55)),ok=btn("熟悉",MINT_SOFT,Color.rgb(35,105,88));bad.setOnClickListener(v->rate(c,false));ok.setOnClickListener(v->rate(c,true));rate.addView(bad,new LinearLayout.LayoutParams(0,dp(54),1));Space sp=new Space(this);rate.addView(sp,new LinearLayout.LayoutParams(dp(10),1));rate.addView(ok,new LinearLayout.LayoutParams(0,dp(54),1));body.addView(rate);}}
    View historyMini(Card c){StudyStore.State s=store.state(c.id);LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);l.setGravity(Gravity.CENTER);for(StudyStore.Rec r:s.history){TextView x=tv(r.ok?"熟":"模",10,r.ok?Color.rgb(38,120,96):Color.rgb(145,74,58),true);x.setGravity(Gravity.CENTER);x.setBackground(bg(r.ok?MINT_SOFT:RED_SOFT,7));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(dp(30),dp(26));p.setMargins(dp(2),dp(8),dp(2),0);l.addView(x,p);}return l;}
    void rate(Card c,boolean ok){engine.rate(c,ok);qIndex++;revealed=false;showReview();}
    void showExample(Card c){JSONObject d=repo.detail(c.topic);String x=d==null?"":d.optString("example");new AlertDialog.Builder(this).setTitle(c.topic+" · 例子").setMessage(x.isEmpty()?"当前资料没有单列例子。":x).setPositiveButton("关闭",null).show();}
    void showFull(Card c){JSONObject d=repo.detail(c.topic);if(d==null)return;String[] labels={"名词解释","简答","论述/案例"},keys={"name","simple","essay"};new AlertDialog.Builder(this).setTitle(c.topic+" · 完整答案").setItems(labels,(dlg,which)->new AlertDialog.Builder(this).setTitle(labels[which]).setMessage(d.optString(keys[which],"暂无")).setPositiveButton("关闭",null).show()).setNegativeButton("关闭",null).show();}
    void showHistory(Card c){StudyStore.State s=store.state(c.id);StringBuilder b=new StringBuilder();int i=1;SimpleDateFormat f=new SimpleDateFormat("MM-dd HH:mm",Locale.getDefault());for(StudyStore.Rec r:s.history)b.append(i++).append(". ").append(r.ok?"熟悉":"不清楚").append("  ").append(f.format(new Date(r.ts))).append("\n");if(s.history.isEmpty())b.append("暂无记录");b.append("\n薄弱度：").append(Math.round(engine.difficulty(c)*100)).append("%");new AlertDialog.Builder(this).setTitle("最近10次 · "+c.topic).setMessage(b.toString()).setPositiveButton("关闭",null).show();}
    void showBooks(){shell("Books");EditText search=new EditText(this);search.setHint("搜索题目或知识点");search.setSingleLine(true);search.setBackground(bg(SURFACE,14));search.setPadding(dp(14),0,dp(14),0);body.addView(search,new LinearLayout.LayoutParams(-1,dp(52)));LinearLayout metrics=new LinearLayout(this);metrics.setOrientation(LinearLayout.HORIZONTAL);metrics.addView(stat("复习量",store.reviewGoal(),store.reviewGoal()),new LinearLayout.LayoutParams(0,-2,1));metrics.addView(stat("新学量",store.newGoal(),store.newGoal()),new LinearLayout.LayoutParams(0,-2,1));margin(metrics,0,10,0,8);body.addView(metrics);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);body.addView(list);Runnable fill=()->{list.removeAllViews();String key=search.getText().toString().trim();Map<String,List<Card>> groups=new LinkedHashMap<>();for(Card c:repo.cards){if(!key.isEmpty()&&!c.topic.contains(key)&&!c.question.contains(key))continue;String g=c.topic.startsWith("第")?"教材章节":"真题理论专题";groups.computeIfAbsent(g,k->new ArrayList<>()).add(c);}for(Map.Entry<String,List<Card>> e:groups.entrySet()){TextView h=tv(e.getKey(),15,MINT,true);margin(h,0,16,0,7);list.addView(h);Map<String,List<Card>> byTopic=new LinkedHashMap<>();for(Card c:e.getValue())byTopic.computeIfAbsent(c.topic,k->new ArrayList<>()).add(c);for(Map.Entry<String,List<Card>> t:byTopic.entrySet()){LinearLayout row=box(SURFACE,13,14);int mast=0,fam=0,fuz=0,un=0;for(Card c:t.getValue()){String tag=store.state(c.id).tag;if(tag.equals("掌握"))mast++;else if(tag.equals("熟悉"))fam++;else if(tag.equals("模糊"))fuz++;else un++;}row.addView(tv(t.getKey(),17,INK,true));row.addView(tv("掌握 "+mast+"  熟悉 "+fam+"  模糊 "+fuz+"  未学习 "+un,12,MUTED,false));row.setOnClickListener(v->{queue=new ArrayList<>(t.getValue());Collections.shuffle(queue);qIndex=0;revealed=false;showReview();});margin(row,0,0,0,7);list.addView(row);}}};fill.run();search.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){fill.run();}public void afterTextChanged(android.text.Editable e){}});}
    void showStats(){shell("统计");int mast=0,fam=0,fuz=0,un=0;for(Card c:repo.cards){String tag=store.state(c.id).tag;if(tag.equals("掌握"))mast++;else if(tag.equals("熟悉"))fam++;else if(tag.equals("模糊"))fuz++;else un++;}LinearLayout g=box(SURFACE,18,18);g.addView(tv("累计复习  "+store.totalReviews(),24,INK,true));g.addView(tv("今日：复习 "+store.todayReview()+" / "+store.reviewGoal()+"   新学 "+store.todayNew()+" / "+store.newGoal(),14,MUTED,false));margin(g,0,0,0,12);body.addView(g);body.addView(stat("掌握",mast,repo.cards.size()));body.addView(stat("熟悉",fam,repo.cards.size()));body.addView(stat("模糊",fuz,repo.cards.size()));TextView h=tv("当前最薄弱的10张卡",18,INK,true);margin(h,0,20,0,8);body.addView(h);List<Card> weak=new ArrayList<>(repo.cards);weak.sort((a,b)->Double.compare(engine.difficulty(b),engine.difficulty(a)));for(int i=0;i<Math.min(10,weak.size());i++){Card c=weak.get(i);LinearLayout r=box(SURFACE,12,12);r.addView(tv(c.question,15,INK,true));r.addView(tv("薄弱度 "+Math.round(engine.difficulty(c)*100)+"% · "+c.topic,11,MUTED,false));r.setOnClickListener(v->{queue=new ArrayList<>();queue.add(c);qIndex=0;revealed=false;showReview();});margin(r,0,0,0,6);body.addView(r);}}
    void showSettings(){shell("我的");LinearLayout s=box(SURFACE,16,18);s.addView(tv("每日学习设置",19,INK,true));s.addView(tv("复习量",13,MUTED,false));EditText r=new EditText(this);r.setInputType(2);r.setText(String.valueOf(store.reviewGoal()));s.addView(r);s.addView(tv("新学量",13,MUTED,false));EditText n=new EditText(this);n.setInputType(2);n.setText(String.valueOf(store.newGoal()));s.addView(n);Button save=btn("保存设置",MINT,Color.WHITE);margin(save,0,10,0,0);save.setOnClickListener(v->{int rv=parse(r,30),nv=parse(n,15);store.setGoals(Math.max(5,Math.min(300,rv)),Math.max(0,Math.min(200,nv)));queue.clear();Toast.makeText(this,"已保存",Toast.LENGTH_SHORT).show();showSettings();});s.addView(save);body.addView(s);LinearLayout info=box(SURFACE,16,18);margin(info,0,12,0,0);info.addView(tv("智能复习规则",18,INK,true));info.addView(tv("• 每张卡保留最近10次熟悉/不清楚记录\n• 最近的不清楚权重更高\n• 薄弱卡当天最多出现2—3次\n• 与到期时间共同决定复习顺序\n• 所有数据仅保存在本机",14,MUTED,false));body.addView(info);Button reset=btn("清空学习进度",RED_SOFT,Color.rgb(130,70,55));margin(reset,0,18,0,0);reset.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("确认清空？").setMessage("将删除所有学习记录和每日设置。").setNegativeButton("取消",null).setPositiveButton("清空",(d,w)->{store.clearAll();queue.clear();showSettings();}).show());body.addView(reset);}
    int parse(EditText e,int def){try{return Integer.parseInt(e.getText().toString());}catch(Exception x){return def;}}
}
